export const ROOM_FETCH_REQUEST = 'ROOM_FETCH_REQUEST';
export const ROOM_FETCH_SUCCESS = 'ROOM_FETCH_SUCCESS';
export const ROOM_FETCH_ERROR = 'ROOM_FETCH_ERROR';
export const ROOM_SET_ALERT = 'ROOM_SET_ALERT';
export const ROOM_REMOVE_ALERT = 'ROOM_REMOVE_ALERT';
export const ROOM_REQUEST_CONVERSATION = 'ROOM_REQUEST_CONVERSATION'; 
export const ROOM_SET_CONVERSATION = 'ROOM_SET_CONVERSATION';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';